from fastapi import APIRouter, HTTPException, Depends
from sqlmodel import Session, select
from database import get_session
from models import Target, Campaign, AuditLog
from pydantic import BaseModel
from jose import jwt, JWTError
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import os

router = APIRouter(prefix="/targets", tags=["targets"])
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = "HS256"
security = HTTPBearer()

def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        user_id = int(payload.get("sub"))
        role = payload.get("role")
        return {"user_id": user_id, "role": role}
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid or expired token")

class TargetCreate(BaseModel):
    first_name: str
    last_name: str
    email: str
    department: str

def target_to_dict(t):
    return {
        "id": t.id,
        "campaign_id": t.campaign_id,
        "first_name": t.first_name,
        "last_name": t.last_name,
        "email": t.email,
        "department": t.department,
        "tracking_uuid": t.tracking_uuid,
        "training_completed": t.training_completed,
        "created_at": str(t.created_at)
    }

@router.post("/{campaign_id}/targets")
def add_target(
    campaign_id: int,
    req: TargetCreate,
    session: Session = Depends(get_session),
    current_user: dict = Depends(get_current_user)
):
    # Make sure campaign exists
    campaign = session.get(Campaign, campaign_id)
    if not campaign:
        raise HTTPException(status_code=404, detail="Campaign not found")

    target = Target(
        campaign_id=campaign_id,
        first_name=req.first_name,
        last_name=req.last_name,
        email=req.email,
        department=req.department
        # tracking_uuid is auto-generated by the model!
    )
    session.add(target)
    session.commit()
    session.refresh(target)

    log = AuditLog(
        user_id=current_user["user_id"],
        action="target_added",
        detail="Target " + req.email + " added to campaign " + str(campaign_id)
    )
    session.add(log)
    session.commit()

    return target_to_dict(target)

@router.get("/{campaign_id}/targets")
def list_targets(
    campaign_id: int,
    session: Session = Depends(get_session),
    current_user: dict = Depends(get_current_user)
):
    targets = session.exec(
        select(Target).where(Target.campaign_id == campaign_id)
    ).all()
    return [target_to_dict(t) for t in targets]